image:
  file: .gitpod.Dockerfile
tasks:
  # - name: upgrade dart
  #   init: |
  #     brew update
  #     brew upgrade dart

  - command: dart Hello.dart

  - name: Get packages
    command: |
      cd solid_principles/
      dart pub get

vscode:
  extensions:
    - dart-code.dart-code
